# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: ManualReleaseTag

permissions: write-all

on:
  workflow_dispatch:

jobs:
  # Releases new Python version
  Release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify all python versions you might want to perform the actions on
        python-version: [ "3.11" ]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get version
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: version
        run: |
          version=$(python .github/get_version.py)
          echo "BUMPED_VERSION=$(echo v$version)" >> $GITHUB_ENV
          echo "New version: $version"
      - name: Create Release
        run: gh release create ${{ env.BUMPED_VERSION }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
